language: node_js
node_js:
- '4.2'
sudo: false
addons:
  apt:
    packages:
    - graphviz
deploy:
  provider: npm
  email: jononor@gmail.com
  api_key:
    secure: Y/CEf+Yr6Ri5qsofLsSG6X/fHVkCiOr/hilLCnNNS8ZIPl2XBSHRD8ZCt0J/9DiTYUYzd01khQBINJJuhCAI1oVv8teIcGWBWcdFkcJsC8PXJx39EqhEdNC/0hvZ+qxEnF0XDu7N6XUFBcsPWQ3QNV3dpJJsrxDoDgfB+Z1cu+s=
  on:
    tags: true
    repo: jonnor/finito
